### ISSUE TITLE
demo-android has issuing in build

### ISSUE THREAD

**Issue by ALAlliancetek** [ricohapi/theta-client#1]
when we import the [demo-android](https://github.com/ricohapi/theta-client/tree/main/demos/demo-android), we faced the project build failure with the error.

   ```
 theta-client-main\theta-client-main\demos\demo-android\app\libs\theta-client-debug.aar.
    > zip END header not found
```

and we also found that

   ` theta-client-main\theta-client-main\demos\demo-android\app\libs\theta-client-debug.aar`

was not defined in app level `build.gradle`

we also run the below command, but nothing happened.

   ` ./gradlew publishToMavenLocal`

so how we resolve the build failure issue?

**Comment by simago** [comment]
First, build theta-client and generate `theta-client-debug.aar`.
Second, put the `theta-client-debug.aar` on `theta-client-main\theta-client-main\demos\demo-android\app\libs`.
Then you can build demo-android.

Alternatively, wait for preparing to install theta-client.aar from Maven.  We would announce it soon.

**Comment by ALAlliancetek** [comment]
@simago - Thanks !! Project build successfully, but sometime preview is not displaying in `demo-android `
Also as of now we use [theta-api2.1-android-sdk](https://github.com/ricohapi/theta-api2.1-android-sdk) for capturing image and we are facing memory consumption [issue ](https://community.theta360.guide/t/glphotoactivity-java-consume-more-memory-on-android-devices/8794)while we load the preview of image after capturing, so this [issue ](https://community.theta360.guide/t/glphotoactivity-java-consume-more-memory-on-android-devices/8794)is also we faced in this client library as well, so how we reduce the memory usage or memory consumption during image load and try to capture more photo using RICOH 360 device.

**Comment by simago** [comment]
When I use `demo-android` with THETA SC2 connected to PC using a USB cable, preview is not displayed.  When disconnected to PC, no problem.

And I read your [issue](https://community.theta360.guide/t/glphotoactivity-java-consume-more-memory-on-android-devices/8794).  This theta client does not depend on [theta-api2.1-android-sdk](https://github.com/ricohapi/theta-api2.1-android-sdk).  I tried to capture 20 photos using `demo-android`, but memory usage was not increased ( average 128MB, peak time under 200MB).

**Comment by ALAlliancetek** [comment]
@simago - I mean to say it's internally use the HttpConnection and the [theta-api2.1-android-sdk](https://github.com/ricohapi/theta-api2.1-android-sdk) was also internally used HttpConnections.
I already know this is the only way to do operations with camera but this [theta-client](https://github.com/ricohapi/theta-client) is only provides a better way to control the camera.

One of our client is totally depend on high usage of 360 camera through the android native application for their business and they faces the laggy performance while frequently use the camera so we want to provide a better solution with 360 camera performance

And I was not connected the camera using USB cable but still the preview is not displayed every time.

Also the memory consumption is not peak on every time but many time we noticed that the memory used by the Image preview is not releasing after the preview stop

**Comment by simago** [comment]
@ALAlliancetek  Thank you for capturing the video.  I understand your situation.
I try to investing preview problems.

**Comment by simago** [comment]
@ALAlliancetek  We fixed the issue where live preview sometimes does not start with THETA SC2.
