### ISSUE TITLE
flutter client  ThetaWebApiException cant start preview

### ISSUE THREAD

**Issue by shougonyiren** [ricohapi/theta-client#12]
![bd580031-04c2-463e-9cf7-bb5d20b166fb](https://user-images.githubusercontent.com/30143232/225849723-bb0aa5fa-4468-4944-8100-109c28cf42ea.jpeg)

**Comment by simago** [comment]
Would you tell me the OS and Theta model you use?

**Comment by shougonyiren** [comment]
> 
huawei mate30  理光Theta Z1

**Comment by codetricity** [comment]
I'm still getting this type of error with both SC2 and Z1.

* Pixel 2 physical device, Android 11
* Z1 fw 2.20.3
* SC2 fw 1.82

![image](https://user-images.githubusercontent.com/5799860/230213983-cacbc16e-97ec-46d5-a9a5-f83aa918b70b.png)

**Comment by simago** [comment]
@codetricity 
Flutter sample application didn't stop preview befor shooting.  It is fixed in #22.

**Comment by codetricity** [comment]
this works well for me now.

Build was easy with no problems.  Just had to add mavenLocal() to android/build.gradle

https://youtube.com/shorts/qSE0BHCdyEc
