### ISSUE TITLE
flutter  recommend panorama  https://pub.flutter-io.cn/packages/panorama

### ISSUE THREAD

**Issue by shougonyiren** [ricohapi/theta-client#13]
![PM54QkFr3O](https://user-images.githubusercontent.com/30143232/226553868-9142c54f-593b-4cbb-96f7-bc10149ff239.jpg)
![pOSSOXyITZ](https://user-images.githubusercontent.com/30143232/226553892-25683aa9-7846-4915-8e6e-b8c3d0665f96.jpg)
![image](https://user-images.githubusercontent.com/30143232/226553984-11c6fe02-2a25-4cd2-8a6c-1a8e71f7cdee.png)

**Comment by shougonyiren** [comment]
> 

Just suggestions

**Comment by codetricity** [comment]
@shougonyiren , thank you for providing this tip as I was thinking of trying this myself.  It is good to know it worked for you.  :-)

Can you navigate in the livepreview when you use panorama?

Also, have you managed to play a 360 video from file in Flutter?

I am currently using this package: https://github.com/kilroy80/flutter_video_360

However, it requires a http endpoint and I want to play the 360 video from a locally stored file on Android.

**Comment by shougonyiren** [comment]
> @shougonyiren
> 
> It works great, thanks. https://youtu.be/BE9nvj7WS8M
> 
> However, after I take a picture, I'm getting this error. Have you seen this error yourself?
> 
> ![image](https://user-images.githubusercontent.com/5799860/226971844-1fe9635a-3e06-4937-971d-f1652f07eca7.png)
> 
> ```dart
> //photo_screen.dart
> ...
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>         appBar: AppBar(title: Text('Photo: $name')),
>         body: Container(
>             alignment: Alignment.center,
>             child: Panorama(
>               child: Image.network(
>                 fileUrl,
>                 loadingBuilder: (context, child, loadingProgress) {
>                   if (loadingProgress == null) return child;
>                   return const Text('loading...');
>                 },
>                 errorBuilder: (a, b, c) {
>                   return Container(
>                     color: Colors.white,
>                   );
>                 },
>               ),
>             )));
>   }
> ```

I actually encountered this problem too. I'll let you know once I solve it. For now, I'm choosing to ignore the pop-up window. Even if you don't click on the pop-up window, it will still attempt to take the picture and redirect you to the page once the picture is taken.

**Comment by shougonyiren** [comment]
> > @shougonyiren
> > It works great, thanks. https://youtu.be/BE9nvj7WS8M
> > However, after I take a picture, I'm getting this error. Have you seen this error yourself?
> > ![image](https://user-images.githubusercontent.com/5799860/226971844-1fe9635a-3e06-4937-971d-f1652f07eca7.png)
> > ```dart
> > //photo_screen.dart
> > ...
> >   @override
> >   Widget build(BuildContext context) {
> >     return Scaffold(
> >         appBar: AppBar(title: Text('Photo: $name')),
> >         body: Container(
> >             alignment: Alignment.center,
> >             child: Panorama(
> >               child: Image.network(
> >                 fileUrl,
> >                 loadingBuilder: (context, child, loadingProgress) {
> >                   if (loadingProgress == null) return child;
> >                   return const Text('loading...');
> >                 },
> >                 errorBuilder: (a, b, c) {
> >                   return Container(
> >                     color: Colors.white,
> >                   );
> >                 },
> >               ),
> >             )));
> >   }
> > ```
> 
> I actually encountered this problem too. I'll let you know once I solve it. For now, I'm choosing to ignore the pop-up window. Even if you don't click on the pop-up window, it will still attempt to take the picture and redirect you to the page once the picture is taken.

@codetricity
