### ISSUE TITLE
Unresolved references problem

### ISSUE THREAD

**Issue by jsantamariag** [ricohapi/theta-client#16]
Hello! I'm having the same problem over and over again that makes me unable to use the package :(

I have tried both running the demo-flutter and creating a project to add the theta_client_flutter package to it and use it, but in both cases, once everything is set up, built without errors and I try to run, i get the same problems:

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
e: C:\Users\Javier\StudioProjects\theta-client\demos\demo-flutter\your_app_name\packages\theta_client_flutter\android\src\main\kotlin\com\ricoh360\thetaclient\theta_client_flutter\ConvertUtil.kt: (11, 37): Unresolved reference: manufacturer
e: C:\Users\Javier\StudioProjects\theta-client\demos\demo-flutter\your_app_name\packages\theta_client_flutter\android\src\main\kotlin\com\ricoh360\thetaclient\theta_client_flutter\ConvertUtil.kt: (14, 39): Unresolved reference: wlanMacAddress
e: C:\Users\Javier\StudioProjects\theta-client\demos\demo-flutter\your_app_name\packages\theta_client_flutter\android\src\main\kotlin\com\ricoh360\thetaclient\theta_client_flutter\ConvertUtil.kt: (15, 44): Unresolved reference: bluetoothMacAddress
e: C:\Users\Javier\StudioProjects\theta-client\demos\demo-flutter\your_app_name\packages\theta_client_flutter\android\src\main\kotlin\com\ricoh360\thetaclient\theta_client_flutter\ConvertUtil.kt: (17, 35): Unresolved reference: supportUrl
e: C:\Users\Javier\StudioProjects\theta-client\demos\demo-flutter\your_app_name\packages\theta_client_flutter\android\src\main\kotlin\com\ricoh360\thetaclient\theta_client_flutter\ConvertUtil.kt: (21, 28): Unresolved reference: api
e: C:\Users\Javier\StudioProjects\theta-client\demos\demo-flutter\your_app_name\packages\theta_client_flutter\android\src\main\kotlin\com\ricoh360\thetaclient\theta_client_flutter\ConvertUtil.kt: (22, 24): Not enough information to infer type variable V
e: C:\Users\Javier\StudioProjects\theta-client\demos\demo-flutter\your_app_name\packages\theta_client_flutter\android\src\main\kotlin\com\ricoh360\thetaclient\theta_client_flutter\ConvertUtil.kt: (23, 37): Unresolved reference: endpoints
e: C:\Users\Javier\StudioProjects\theta-client\demos\demo-flutter\your_app_name\packages\theta_client_flutter\android\src\main\kotlin\com\ricoh360\thetaclient\theta_client_flutter\ConvertUtil.kt: (24, 44): Unresolved reference: endpoints
e: C:\Users\Javier\StudioProjects\theta-client\demos\demo-flutter\your_app_name\packages\theta_client_flutter\android\src\main\kotlin\com\ricoh360\thetaclient\theta_client_flutter\ConvertUtil.kt: (26, 33): Unresolved reference: apiLevel

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':theta_client_flutter:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

As you guys can see, some references are not being resolved. I've navigated through the project and noticed that "manufacturer" and rest of references are inside ThetaInfo class in theta_client_flutter.dart.
Something is going wrong and I don't know what it is.

Hope someone can give any clue. Thanks!

**Comment by codetricity** [comment]
I have demo-flutter working with no problems with a Windows 11 build.

https://youtu.be/dJV5s46xFA0

I also built a brand new Flutter app from scratch using the theta-client library (not based on the demo-flutter example) using `flutter create --platforms=android -a 

https://youtu.be/EAwT2j0x5VU

I've documented the process of using release .1.0.0 library with a new project at the link below with the full code using Flutter 3.7.7 and dart 2.19.4:

https://github.com/codetricity/theta_client_minimal/blob/main/README.md


If the build fails, make sure you have the aar files accessible in packages/theta_client_flutter/android/aar

Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
main.dart:1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform theta-client-debug.aar to match attributes {artifactType=android-a

**Comment by simago** [comment]
@jsantamariag @codetricity It seems that theta-client v1.0.0 on maven central is referenced.
Would you try add maven local to demo-flutter/android/build.gradle like this:
```
allprojects {
    repositories {
        mavenLocal()
        google()
        mavenCentral()
    }
}
```

**Comment by codetricity** [comment]
This worked for me building on Windows 11 and deploying to Pixel 2 physical device (Android 11).   I'm using the latest commits as of ceb425fa5de7cffcfd4459fb77d1b0753b2b60b1  (April 2nd, 2023 version).
