### ISSUE TITLE
EV値のSetOptionsに失敗する

### ISSUE THREAD

**Issue by kksk-github** [ricohapi/theta-client#2]
SetOptionsでEV値を設定しようとした際、下記エラーログが出る。ISO値を設定した場合は成功する。
```
[Error: No enum constant com.ricoh360.thetaclient.ThetaRepository.ExposureCompensationEnum.P_2_0]
```
コードは以下
```
      const options: Options = {iso: IsoEnum.ISO_2000};
      setOptions(options).then(...
```

**Comment by simago** [comment]
react-native/src/index.tsxの`ExposureCompensationEnum`の定義で、`P2_0`とすべき所が誤って`P_2_0`となっていました。修正します。

**Comment by simago** [comment]
Fixed by https://github.com/ricohapi/theta-client/commit/4c2ffcdbc90b409ee623443949d2b379c50bb13a
