### ISSUE TITLE
Getting jitters in live preview in react native (platform android)

### ISSUE THREAD

**Issue by kishanj918** [ricohapi/theta-client#27]

**Comment by simago** [comment]
The demo application displays each frame of live preview simply using `<image source={data URL of a frame}>`.   Some components for display may be needed.

Adding `fadeDuration={0}` to `<image>`, duration for displaying each frame gets liittle longer. 
The 54th line of demos/demo-react-native/src/TakePhoto.tsx like this:
```
<Image style={styles.takePhoto} source={{uri: dataUrl}} fadeDuration={0} />
```

**Comment by codetricity** [comment]
I can replicate the problem, but do not have a solution at the moment.

https://youtu.be/roOYmw5ZmfA

I hope to try the package below in the future:

https://github.com/Segware/react-native-mjpeg-player

There may be an algorithm to hold the previous frame until the current frame has finished loading.  Flutter had gapless playback.  Maybe React Native `<Image />` has a similar property or if not, maybe an existing package can buffer the frames.  If you find a solution, please post.

**Comment by codetricity** [comment]
It works great now.  Thanks for all your work!  I tested it with physical device Google Pixel 4a and made a video.  https://youtu.be/NsfKQiChcOg
