### ISSUE TITLE
GetOptionsの引数が1つしか設定できない

### ISSUE THREAD

**Issue by kksk-github** [ricohapi/theta-client#3]
tutorialに記載されているコードはそのままビルドが通らない。
https://github.com/ricohapi/theta-client/blob/main/docs/tutorial-react-native.ja.md#%E3%82%AB%E3%83%A1%E3%83%A9%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%82%92%E5%8F%96%E5%BE%97%E3%81%99%E3%82%8B

要素を1つにするとビルドが通る、引数の型の問題と思われる。
```
const optionNames: [OptionNameEnum] = [OptionNameEnum.Iso];
getOptions(optionNames).then(...
```

**Comment by simago** [comment]
`[OptionNameEnum]`は誤りで`OptionNameEnum[]`にすべきですね。他にも同様の誤りがあるので修正します。

**Comment by kksk-github** [comment]
v1.0.2にて修正されたことを確認しました。
