### ISSUE TITLE
Flutter demo release build - can't initialize

### ISSUE THREAD

**Issue by jcasman** [ricohapi/theta-client#33]
The apk built with `flutter build apk` can't initialize the connection to the camera, gets "initialize error" - I'm using demo-flutter with no changes. Google Pixel 4 running Android 13. With THETA X. Firmware 2.10.1.

This works in debug with no problem. I only have the problem when I build for release and distribution.

![Screenshot_20230622-160936](https://github.com/ricohapi/theta-client/assets/1075520/640f87e8-1316-40ea-8b95-0f5be8f51267)

![Screenshot_20230622-160949](https://github.com/ricohapi/theta-client/assets/1075520/150d9330-2bc0-4043-b47a-478e300c653c)

**Comment by simago** [comment]
@jcasman Thank you for your defect report. I confirm  "initialize error"  in release mode. 

To fix this error:
1. Add file "proguard-rules.pro" to "theta-client/demos/demo-flutter/android/app/", which content is following:
```
-keep class com.ricoh360.thetaclient.** { *; }
```
2. Add following property `proguardFiles` to "theta-client/demos/demo-flutter/android/app/build.gradle":
```
android {
  buildTypes {
    release {

      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

    }
  }
}

```

We will fix this defect in the next release.

**Comment by jcasman** [comment]
This fix worked. Thank you!
