### ISSUE TITLE
search device and chose device to conect app with react-native

### ISSUE THREAD

**Issue by linhndbtc-studio** [ricohapi/theta-client#39]
How to proactively connect to device theta 360 via react native

I want to create a section to find a list of devices and select a device that actively connects to my react native. I have read the docs and can't find a solution. Please help me if possible. Thank you.

**Comment by simago** [comment]
[react-native-wifi-reborn](https://github.com/JuanSeBestia/react-native-wifi-reborn) may be helpful for you.
