### ISSUE TITLE
Set `imageStitching` params from flutter controller

### ISSUE THREAD

**Issue by ubi15** [ricohapi/theta-client#40]
Hi all,
I am loving this repository (ies), a lot of clean and well documented examples to play around with our Ricoh Theta.

I am trying to control the image stitching (on a theta V) parameter in the photo mode, especially to set it to `None` to speed up the inter-time between two pictures.

I did not find it in the options that can be set in the `photoCaptureBuilder` but I get the feeling that this limitation is only due to the fact that:
1. the `imageStitching` setting is not exposed by the `OptionNameEnum` and,
2. there is no `imageStitchingEnum` to store the values 

(By the way, which would be the correct parameter name to pass to the camera to manage the stitching?)

So far I only found [this example](https://community.theta360.guide/t/android-app-to-manage-in-camera-stitching-top-bottom-correction-and-reset/5656) but with no code attached.

I would like to know, in your more experienced view, which is the best:
1. Add the enums to also manage the stitching option on the client side or
2. add a method to the flutter interface to enable passing transferred options as in the [pure-Android](https://github.com/ricohapi/theta-client/tree/main/demos/demo-android/app/src/main/java/com/ricoh360/thetaclient/thetaClientDemo) example?

In either the cases I will try to implement it and make a pull request to get this feature.

Thanks in advance for your help.

**Comment by codetricity** [comment]
I do not work for RICOH.  I'm just a normal guy that is using theta-client.

> (By the way, which would be the correct parameter name to pass to the camera to manage the stitching?)

https://github.com/ricohapi/theta-api-specs/blob/main/theta-web-api-v2.1/options/_image_stitching.md

**Comment by simago** [comment]
@ubi15 We are implementing `ImageStitchingEnum` and include in the next release.

**Comment by ubi15** [comment]
Thanks a lot for your replies!

Do you have an estimation of the time plan of the next release?

Could I help in any way implementing it (you can share a branch to work on).

Thanks again for your help and work.

Il gio 31 ago 2023, 07:03 simago ***@***.***> ha scritto:

**Comment by simago** [comment]
@ubi15 We plan to release until the week of Sept. 11.
Implementation of imageStitching has been completed but we still have a few issues.

**Comment by simago** [comment]
[1.4.0](https://github.com/ricohapi/theta-client/releases/tag/1.4.0) has supported imageStitching.

**Comment by simago** [comment]
[1.4.0](https://github.com/ricohapi/theta-client/releases/tag/1.4.0) has supported imageStitching.
