### ISSUE TITLE
Support for Windows Desktop Application Development?

### ISSUE THREAD

**Issue by jcasman** [ricohapi/theta-client#46]
Kotlin Multiplatform appears as if it can support Windows desktop. The documentation has [a section on desktop applications](https://kotlinlang.org/docs/multiplatform.html#desktop-applications). Will theta-client compile for Windows? Has this been done?

**Comment by simago** [comment]
@jcasman
As you can see from [build.gradle](https://github.com/ricohapi/theta-client/blob/main/kotlin-multiplatform/build.gradle.kts), Theta-client compiles only for Android and iOS.
We have not yet tried to compile for Windows.

**Comment by codetricity** [comment]
@simago do you think it is theoretically possible for another developer to take theta-client, modify build.gradle and compile it for desktop support?  I'm thinking of paying three junior developers to look into kotlin multiplatform desktop builds for a few days.
Based on the article below, I found some information on compose-multiplatform configuration.

https://stackoverflow.com/questions/71987995/how-to-deliver-a-desktop-app-of-kotlin-multiplatform-project

I'm thinking of asking them to go through this information and see if they can first build a standalone Windows desktop app with a simple code example and then if it works, try to use theta-client with the desktop.

https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Native_distributions_and_local_execution

If it is not theoretically possible, I'll assign them different work.

**Comment by simago** [comment]
@codetricity You have a plan to try [Compose Multiplatform](https://www.jetbrains.com/lp/compose-multiplatform/) to generate desktop UI!  It is very interesting project but I have not try.

Using [Kotlin/Native](https://kotlinlang.org/docs/native-dynamic-libraries.html#create-a-kotlin-library), you may compile forked Theta-client into a native dynamic library.  But I do not know an application based on Compose Multiplatform can call a native dynamic library.

**Comment by codetricity** [comment]
@simago thank you for your advice.  Is it theoretically possible to use the native dynamic library as a Flutter plugin, assuming we build the surrounding plugin for Windows platform.

**Comment by simago** [comment]
@codetricity  I found a codelab [Write a Flutter desktop application](https://codelabs.developers.google.com/codelabs/flutter-github-client#0) and [sample desktop application](https://github.com/flutter/samples/tree/main/desktop_photo_search).
It seems that native libraries could be linked to Windows plugin by specifying to `windows/CMakeLists.txt`.
