### ISSUE TITLE
StateでPluginRunning等が取得できない

### ISSUE THREAD

**Issue by kksk-github** [ricohapi/theta-client#5]
Info, Stateの情報で取得出来ないものがある。
https://github.com/ricohapi/theta-client/blob/04cc2848eb85c6fe24c9825928a6956857062fb0/react-native/src/index.tsx#L51

例
```
PluginRunning
```

**Comment by simago** [comment]
Implemented by https://github.com/ricohapi/theta-client/pull/11 and https://github.com/ricohapi/theta-client/pull/15
