### ISSUE TITLE
Preview Client Issue

### ISSUE THREAD

**Issue by dhivya29** [ricohapi/theta-client#58]
@yohei @japboy @togacy @mhirose 
    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?,
    ): View {
        _binding = FragmentThetaCameraBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        lifecycleScope.launch {

            val thetaUrl = "https://fake-theta.vercel.app/"
            val thetaConfig = ThetaRepository.Config()
            thetaConfig.language = ThetaRepository.LanguageEnum.EN_US
            thetaConfig.shutterVolume = 40 // 0 to 100
            thetaConfig.sleepDelay = ThetaRepository.SleepDelayEnum.SLEEP_DELAY_5M
            thetaConfig.offDelay = ThetaRepository.OffDelayEnum.DISABLE
            thetaRepository = newInstance(thetaUrl, thetaConfig)
            thetaRepository?.getOptions(
                listOf(
                    ThetaRepository.OptionNameEnum.CameraMode,
                    ThetaRepository.OptionNameEnum.PreviewFormat,
                    ThetaRepository.OptionNameEnum.CameraControlSource,
                    ThetaRepository.OptionNameEnum.CaptureMode
                )
            )?.let { thetaRepository?.setOptions(it)

            }
        }

   
       
         startPreview()
    }

  private fun startPreview() {
           lifecycleScope.launch {
               try {
                   thetaRepository?.getLivePreview()?.collect { byteReadPacket ->

                       if (isActive) {
                           byteReadPacket.inputStream().use {
                               val bitmap = BitmapFactory.decodeStream(byteReadPacket.inputStream())

/                                   Glide.with(requireContext())
//                                       .load(bitmap)
//                                       .into(binding.imgTheta)
                               byteReadPacket.release()
                           }
                       } else {
                           Log.e("ThetaCameraFragment", "FALSE")

                       }
                   }
               } catch (e: Exception) {
                   Log.e("ThetaCameraFragment", "Error during live preview: ${e.message}", e)
                   // Handle the error as needed
               }
           }
       }

With this code preview client is not worked
Kindly let me know the process of initializing preview Client

**Comment by simago** [comment]
@dhivya29 You use [fake theta](https://github.com/ricohapi/fake-theta).  Its protocol is https but theta client preview function does not support https.

**Comment by dhivya29** [comment]
> @dhivya29 You use [fake theta](https://github.com/ricohapi/fake-theta). Its protocol is https but theta client preview function does not support https.

When i use real ip address of the device with theta client means it will work or not?
I have downloaded demo app too and in that also preview is not working why?

**Comment by simago** [comment]
@dhivya29 When using real Theta, preview of the demo should work.
In the next release, Android demo is improved a little.  Please try it.

**Comment by dhivya29** [comment]
> @dhivya29 I tested theta-client with the SC2 and it works on Android native.
> 
> https://youtu.be/shg2kX7Q8pM?si=QwM1gH0puKv0GjkM
> 
> What RICOH THETA model are you using?
> 
> Note that I don't work for RICOH.

@codetricity 
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        generalViewModel = ViewModelProvider(this).get(GeneralViewModel::class.java)
        lifecycleScope.launch {
            try {
               //val thetaUrl = "https://fake-theta.vercel.app/"
                val thetaUrl = "http://192.168.1.1:80/"
                val thetaConfig = ThetaRepository.Config()
                thetaConfig.language = ThetaRepository.LanguageEnum.EN_US
                thetaConfig.shutterVolume = 40 // 0 to 100
                thetaConfig.sleepDelay = ThetaRepository.SleepDelayEnum.SLEEP_DELAY_5M
                thetaConfig.offDelay = ThetaRepository.OffDelayEnum.DISABLE
                thetaRepository = newInstance(thetaUrl)
                startThetaPreview()
                previewFlow.collectLatest {
                    Glide.with(requireContext()).load(it).into(binding.imgTheta)

                }

            }catch (e:Exception){
                Toast(requireContext()).showCustomToast(
                    e.message.toString(),
                    requireActivity()
                )
            }
        }
        (activity as MainActivity).binding.homeProgressBar.visibility = View.GONE
        binding.imgBack.setOnClickListener {
            dismiss()
        }
     

    }


 

    private fun startThetaPreview() {
        previewJob?.let {
            return
        }
        previewJob = lifecycleScope.launch(Dispatchers.IO) {
            kotlin.runCatching {
                thetaRepository?.getLivePreview()?.collect { byteReadPacket ->
                    ensureActive()
                    byteReadPacket.inputStream().use {
                        _previewFlow.emit(BitmapFactory.decodeStream(it))
                    }
                    byteReadPacket.release()
                }
            }.onFailure {
                when (it) {
                    is CancellationException -> Timber.i(it) // Preview coroutine was cancelled. No need to do anything.
                    else -> Timber.e(it)
                }
            }
        }
    }
    This is how i integrate theta Theta SC2 Firm Version - 01.64
    but preview is not worked but same device works in demo app
