### ISSUE TITLE
Not able to Capture image from camera in release apk in flutter.

### ISSUE THREAD

**Issue by kishanj918** [ricohapi/theta-client#63]
I am calling below code to capture still image. This code works in dev mode but when i tested release apk it is throwing an exception.
```
 photoCapture.takePicture((fileUrl) {
    }, (exception) {
   // getting this error in release apk. works in dev mode.       
    
    // PlatformException(NotConnectedException, com.ricoh360.thetaclient.transferred.UnknownResponse cannot be cast to 
    // com.ricoh360.thetaclient.transferred.TakePictureResponse, null, null)
          });
```

**Comment by simago** [comment]
@kishanj918 I have confirmed to run demo-flutter in release mode without problems.
Would you try to add "proguard-rules.pro" file to your application? Please see [issue #33](https://github.com/ricohapi/theta-client/issues/33#issuecomment-1606426734).

**Comment by LassicYM** [comment]
@kishanj918 

Thanks for your comment.

Could you please output the complete **error log** from Android Studio or console
and share it with us ?

Thank you very much.

**Comment by simago** [comment]
@kishanj918 
Please add following line to your  "proguard-rules.pro" file.
`-keep class kotlinx.serialization.** { *; }`
