### ISSUE TITLE
TakePictureにパラメータを設定できない

### ISSUE THREAD

**Issue by kksk-github** [ricohapi/theta-client#8]
以下のチュートリアルに記載のあるgetPhotoCaptureBuilderのビルドに失敗する。
https://github.com/ricohapi/theta-client/blob/main/docs/tutorial-react-native.ja.md#%E9%9D%99%E6%AD%A2%E7%94%BB%E3%82%92%E6%92%AE%E5%BD%B1%E3%81%99%E3%82%8B

setIsoAutoHighLimit, setFileFormatを抜いて即build()を呼ぶと撮影に成功し、fileUrlまで確認できた。
```
  return getPhotoCaptureBuilder()
    .build()
```

**Comment by simago** [comment]
チュートリアルでは `setFileFormat(PhotoFileFormatEnum.IMAGE_5K)` としていますが、この値はTHETA Z1やXではサポートしていません。
Z1なら `IMAGE_6_7K`、Xなら`IMAGE_5_5K`をお試しください。
機種による差異は[こちら](https://github.com/ricohapi/theta-client/blob/main/docs/tutorial.md#take-photos)に記載してあります。

**Comment by kksk-github** [comment]
カメラ差ではなく、そもそもエラーを吐いておりビルド出来ない状態です。
<img width="672" alt="builder" src="https://user-images.githubusercontent.com/34432339/223639454-ca4b7dc0-f1ca-463e-b5a0-d07543e82bfd.png">

**Comment by simago** [comment]
ご説明ありがとうございます。修正中です。

**Comment by simago** [comment]
Fixed by https://github.com/ricohapi/theta-client/commit/241b8a78ad0d4d089a7272febc7d665084371e99
