### ISSUE TITLE
About the picture automatic correction problem

### ISSUE THREAD

**Issue by bill19** [ricohapi/theta-client#83]
Hello, I would like to inquire about whether the panoramic camera has an automatic correction feature, or if there is an API available to obtain the camera's horizontal offset angle. Currently, we are encountering an issue where the images captured using the Z1/SC2 models have a certain degree of tilt. In order to enhance the output quality and reduce user intervention, we are exploring ways to automatically correct the horizontal alignment of these images. Alternatively, if you have a more suitable solution to address this issue, we would be grateful to hear about it. Currently, we have purchased and are utilizing over 5,000 Z1/SC2 cameras. We look forward to your response.

**Comment by simago** [comment]
@bill19 Sorry for the late response.  Would you please send a mail to  [communication-jp@ricoh360.com](mailto:communication-jp@ricoh360.com), Ricoh support team.

**Comment by simago** [comment]
@bill19 Ricoh support team has sent you a mail.  Would you please respond it.
