### ISSUE TITLE
[Flutter] getOptions "previewFormat" does not work

### ISSUE THREAD

**Issue by xnopre-vrtice** [ricohapi/theta-client#86]
I cannot get "previewFormat", the result is always `null`. 

Code sample : 
```
    final _thetaClientFlutter = ThetaClientFlutter();
    await _thetaClientFlutter.initialize();
    final options = await _thetaClientFlutter.getOptions([OptionNameEnum.previewFormat]);
    debugPrint("previewFormat=${options.previewFormat}");
```

The output is : 
```
previewFormat=null
```

Yet I can see this log : 
```
I/System.out(22912): BODY START
I/System.out(22912): {"name":"camera.getOptions","state":"done","results":{"options":{"remainingSpace":14387511296}}}
I/System.out(22912): BODY END
```

Camera model : RICOH THETA SC2, firmwareVersion:01.71

PS : I can't set "previewFormat" option either...

**Comment by simago** [comment]
@xnopre-vrtice I tried to get option `previewFormat` from Theta SC2 with curl command.
``` bash
$ curl -X POST -H "Content-Type: application/json" -d '{"name":"camera.getOptions","parameters":{"optionNames":["previewFormat"]}}' http://192.168.1.1:80/osc/commands/execute
```
Then I got following response:
``` json
{"name":"camera.getOptions","state":"done","results":{"options":{"previewFormat":{"width":0,"height":0,"framerate":0}}}}
```
Theta client does not expect such a response.
Theta SC2 may not support  option `previewFormat`.

**Comment by xnopre-vrtice** [comment]
Hi @simago ,

Thank you for your answer.

I'm using Flutter`theta-client` with Android (for this tests).

Reading the source code, `w1024_h512_f30` seems to be a supported value for SC2. When I try to set `previewFormat` with the value, I can see the HTTP request with a 200 response status code :
```
{"name":"camera.setOptions","parameters":{"options":{"previewFormat":{"width":1024,"height":512,"framerate":30}}}}
```

After that, I try to read `previewFormat` (with `getOptions(...)`). I can see the HTTP request : 
```
{"name":"camera.getOptions","parameters":{"optionNames":["previewFormat"]}}
```
and then the HTTP response which is different from yours : 
```
{"name":"camera.getOptions","state":"done","results":{"options":{"previewFormat":{"width":512,"height":0,"framerate":30}}}}
```
But in my `Flutter` execution, `previewFormat` is `null`.

The option `previewFormat` seems to be supported by SC2 since I can set and get it, no ?

**Comment by simago** [comment]
@xnopre-vrtice
I confirmed Theta SC2 returned same responses as your observation.
The response for `getOptions` of  `previewFormat` after `setOptions`:
```json
{"width":512,"height":0,"framerate":30}
```
Theta client does not expect the value `0` for `height`.
Theta SC2 does not seem to implement `previewFormat` option correctly.

**Comment by xnopre-vrtice** [comment]
@simago 
Thank you for your test, answer, confirmation and explanation. It's a shame. Is there a solution ? Or somewhere to get more information or discuss about this point ?
Thanks,
Regards
Xavier

**Comment by simago** [comment]
@xnopre-vrtice
[The specification](https://github.com/ricohapi/theta-api-specs/blob/main/theta-web-api-v2.1/options/preview_format.md) of `previewFormat` option does not mention Theta SC2.
I suppose the preview format of Theta SC2 is fixed to:
* width: 1024
* height: 512
* framerate: 30

**Comment by xnopre-vrtice** [comment]
OK thanks. I wanted to try to change the preview format, to have a more fluent stream, but finally, it's OK as it is, it works 👍.

But it seems that SC2 support very few options....

**Comment by xnopre-vrtice** [comment]
The functionality seems to be not supported by SC2 model : I close my issue.
