### ISSUE TITLE
ListFilesにtotalEntriesがない

### ISSUE THREAD

**Issue by kksk-github** [ricohapi/theta-client#9]
https://github.com/ricohapi/theta-client/blob/main/docs/tutorial-react-native.ja.md#theta%E5%86%85%E3%81%AE%E9%9D%99%E6%AD%A2%E7%94%BB%E5%8B%95%E7%94%BB%E3%82%92%E4%B8%80%E8%A6%A7%E3%81%99%E3%82%8B
startCount, entryCountを引数に設定できるが、responseにtotalEntriesが無いためどこまでループを回せば良いのか判断ができない

**Comment by simago** [comment]
Implemented by https://github.com/ricohapi/theta-client/pull/18
