### ISSUE TITLE
demo-ios image viewer use

### ISSUE THREAD

**Issue by codetricity** [ricohapi/theta-client#91]
in demo-ios, in the demos folder, there is this nice example that works great:

https://github.com/ricohapi/theta-client/blob/d1871d69c4bdd6b533b2aaaf16b847db4e0aa690/demos/demo-ios/SdkSample/SphereViewer/html/index.js#L3

Is the code for the `window.RICOH360Viewer;` in this `bundle.js` file?
https://github.com/ricohapi/theta-client/blob/main/demos/demo-ios/SdkSample/SphereViewer/html/bundle.js

If people want to use theta-client demo-ios as a base for their own application,  is there documentation on the parameters for these settings?

```javascript
const viewer = new ViewerContainer({
  div: divElement,
  config: {
    color: {
      background: 'navy',
    },
    controls: {
      scrollZoom: true,
    },
    scene: {
      numOfCache: 3,
    },
    transitionDuration: 5, // millisecond
    view: {
      keepCoords: true,
      limit3D: {
        maxVFov: 2.8, // radian
        minVFov: 0.8,
        maxHFov: 2.8,
      },
    },
  },
  getScene,
});
```

In particular, if the THETA image is stored to camera roll, how is this used?

```javascript
const getScene = async (id) => {
  return {
    id,
    image: {
      type: 'equirect',
      url: getImageUrl(id),
      viewParams: viewParams,
    }
  }
};
```

I think that theta-client is a very useful reference application for the demo components as well as the camera api behavior.  

---

Unrelated to my question about the 360 image viewer in the demo-ios project, I made a video on using demo-ios with Xcode 16.0 and iOS 17.

https://youtu.be/8moKIJ7f8kQ?feature=shared

The viewer worked great in my test.  Live preview also working just fine.

**Comment by simago** [comment]
@codetricity 
> Is the code for the window.RICOH360Viewer; in this bundle.js file?

Yes it is.

> If people want to use theta-client demo-ios as a base for their own application, is there documentation on the parameters for these settings?

We intend to show how to display local 360 degree images on a viewer through this sample application, so we do not have documentation of the viewer.  If you want to use a viewer, you should probably use OSS viewer such as [Marzipano ](https://www.marzipano.net/).

**Comment by codetricity** [comment]
@simago is the situation the same with demo-android?  Do you recommend that developers avoid using the viewer in the bundle.js file, but instead use something like Marzipano in the WebView?  I guess that the main problem is that the viewer in the bundle.js file is not documented?

https://github.com/ricohapi/theta-client/blob/main/demos/demo-android/app/src/main/assets/bundle.js

**Comment by simago** [comment]
@codetricity  Is this comment for https://github.com/ricohapi/theta-client/issues/92 ?
If so, that is not a viewer problem, but a socket communication problem. We are investigating  the problem.

**Comment by codetricity** [comment]
@simago it is not related to #92.  I am making a list of 360 viewers to use on Android.  I am wondering if the demo-android can be used as a reference for a 360 image viewer?  Or, should I let people know that they should look at Marzipano in a WebView when building an Android mobile app to view RICOH THETA images?

**Comment by simago** [comment]
@codetricity I understand your comment.  The viewer of demo-android is intended for demonstration only, so its quality is not good enough.  It would be better to introduce OSS such as Marzipano.

**Comment by codetricity** [comment]
@simago thank you for your answer.  We'll work with some people in the community on producing 360 image viewer examples with Marzipano in the WebView for RICOH customers that want an OSS solution.  I already have an example of [Pannellum in WebView on React Native iOS and Android](https://community.theta360.guide/t/howto-react-native-with-pannellum-360-viewer-with-local-and-network-images/9995?u=craig). 

Note that I also have an example of using the RICOH360 Viewer in a WebView on iOS Swift, but I am waiting to make the repository public.

We are integrating the examples with theta-client.
